version: '3.7'

services:
    api:
        image: api
        build:
            context: ./api
        ports:
            - 3001:3001
        volumes:
            - .:/api
        environment:
            - PORT=3001
            - MONGO_URI=mongodb://192.168.0.37:27017/mnemosyne
            - NODE_ENV=development
    
    dashboard:
        image: dashboard
        build:
            context: ./dashboard
        ports:
            - 8080:3000
        volumes:
            - ./dashboard:/usr/src/dashboard
        environment:
            - NODE_ENV=development
        depends_on: 
            - api
