version: "3.7"

services:
  api:
    image: api
    build:
      context: ./api
    ports:
      - 3001:3001
    volumes:
      - .:/api
    env_file:
      - api.env

  dashboard:
    image: dashboard
    build:
      context: ./dashboard
      args:
        REACT_APP_API_URI: "http://192.168.0.21:3001"
    ports:
      - 8080:3000
    volumes:
      - ./dashboard:/usr/src/dashboard
    env_file:
      - dashboard.env
    depends_on:
      - api

  analytics:
    image: analytics
    build:
      context: ./analytics
    ports:
      - 5000:5000
    volumes:
      - ./analytics:/usr/src/analytics
    env_file:
      - analytics.env
    depends_on:
      - api
